# Generated by Django 2.2.6 on 2020-01-30 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_remove_certifier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(max_length=128)),
                ('certifiers', models.ManyToManyField(to='user_profile.Certifier')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.Recipient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
