# Generated by Django 2.2.6 on 2020-01-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifier',
            name='type',
        ),
    ]
