# Generated by Django 2.2.6 on 2020-01-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200129_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.BinaryField(),
        ),
    ]
