# Generated by Django 2.2.6 on 2020-01-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcertificate',
            name='certifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.Certifier'),
        ),
        migrations.AddField(
            model_name='requestcertificate',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.Recipient'),
        ),
    ]
